// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Archive        string
	ArchiveArtists string
	ArchiveTags    string
	Artist         string
	Circle         string
	Magazine       string
	Parody         string
	Tag            string
}{
	Archive:        "archive",
	ArchiveArtists: "archive_artists",
	ArchiveTags:    "archive_tags",
	Artist:         "artist",
	Circle:         "circle",
	Magazine:       "magazine",
	Parody:         "parody",
	Tag:            "tag",
}
